query getProducts($productsInput:GetProductsInput){
  getProducts(productsInput:$productsInput){
    code
    success
    message
    count,
    products{
      id
      productName
      thumbnail
      description
      price
      offer
      netPrice
      hasMultipleSize
      sizeAndPrice{
        isDefault
        size
        price
        offer
        netPrice
      }
      isAvailable
      category{
        id
        name
      }
    }
  }
}
