query getReservations($input:GetReservationsInput){
  getReservations(input:$input){
    code
    success
    message
    count
    reservations{
      id
      createdAt
      numberOfPeople
      desiredDate
      desiredTime
      reservationStatus
      isPreOrder
      reservedBy{
        id
        firstName
        lastName
        email
        emergencyContactNo
      }
      order{
        items{
          cartItems{
            productId
            productName
            pricePerUnit
            productQuantity
          }
          totalCost
        }
      }
    }
  }
}